SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS p014_membership_transfer;
DROP TABLE IF EXISTS p014_market;
DROP TABLE IF EXISTS p014_notice;
DROP TABLE IF EXISTS p014_qna;
DROP TABLE IF EXISTS p014_user;
DROP TABLE IF EXISTS p014_gym;
DROP TABLE IF EXISTS p014_machine;




/* Create Tables */

CREATE TABLE p014_gym
(
	GYM_CODE int(10) NOT NULL AUTO_INCREMENT,
	GYM_NAME varchar(50) NOT NULL,
	ADDRESS varchar(100) NOT NULL,
	TEL_NO int(15) NOT NULL,
	DESCRIPTION varchar(500) NOT NULL,
	OWNER_ID varchar(15) NOT NULL,
	PRIMARY KEY (GYM_CODE)
);


CREATE TABLE p014_machine
(
	MACHINE_CODE int(10) NOT NULL AUTO_INCREMENT,
	MACHINE_NAME varchar(255) NOT NULL,
	MACHINE_TARGET text NOT NULL,
	PRIMARY KEY (MACHINE_CODE)
);


CREATE TABLE p014_market
(
	MARKET_NO int(10) NOT NULL AUTO_INCREMENT,
	CONTENT text NOT NULL,
	TITLE varchar(200) NOT NULL,
	GYM_CODE int(10) NOT NULL,
	-- 계정의 아이디
	SELLER_ID varchar(15) NOT NULL COMMENT '계정의 아이디',
	-- 계정의 아이디
	BUYER_ID varchar(15) COMMENT '계정의 아이디',
	PRICE int(11) NOT NULL,
	UPLOAD_DATE datetime NOT NULL,
	STRAT_DATE datetime NOT NULL,
	END_DATE datetime NOT NULL,
	STATUS_CODE varchar(10) NOT NULL,
	SOLD_DATE datetime NOT NULL,
	PRIMARY KEY (MARKET_NO)
);


CREATE TABLE p014_membership_transfer
(
	TRANSFER_NO int(10) NOT NULL AUTO_INCREMENT,
	MARKET_NO int(10) NOT NULL,
	STATUS_CODE varchar(10) NOT NULL,
	REQUEST_DATE datetime NOT NULL,
	PROCESS_DATE datetime,
	PRIMARY KEY (TRANSFER_NO)
);


CREATE TABLE p014_notice
(
	NOTICE_NO int(10) NOT NULL AUTO_INCREMENT,
	TITLE varchar(200) NOT NULL,
	CONTENT text NOT NULL,
	GYM_CODE int(10) NOT NULL,
	-- 계정의 아이디
	ID varchar(15) NOT NULL COMMENT '계정의 아이디',
	UPLOAD_DATE datetime NOT NULL,
	PRIMARY KEY (NOTICE_NO)
);


CREATE TABLE p014_qna
(
	QNA_NO int(10) NOT NULL AUTO_INCREMENT,
	-- 계정의 아이디
	QUESTION_ID varchar(15) NOT NULL COMMENT '계정의 아이디',
	QUESTION_TITLE varchar(200) NOT NULL,
	QUESTION_CONTENT text NOT NULL,
	-- 계정의 아이디
	ANSWER_ID varchar(15) COMMENT '계정의 아이디',
	ANSWER_CONTENT text,
	IS_SECRET char(1) NOT NULL,
	QUESTION_DATE datetime NOT NULL,
	ANSWER_DATE datetime,
	PRIMARY KEY (QNA_NO)
);


CREATE TABLE p014_user
(
	-- 계정의 아이디
	ID varchar(15) NOT NULL COMMENT '계정의 아이디',
	-- 계정의 비밀번호
	PW varchar(20) NOT NULL COMMENT '계정의 비밀번호',
	-- 계정주의 이름
	-- 
	NAME varchar(15) NOT NULL COMMENT '계정주의 이름
',
	-- 계정주의 전화번호
	PHONE_NO int(15) NOT NULL COMMENT '계정주의 전화번호',
	-- 계정의 유형(Admin / User)
	ROLE_TYPE varchar(10) NOT NULL COMMENT '계정의 유형(Admin / User)',
	GYM_CODE int(10),
	PROFILE_PATH varchar(255),
	PRIMARY KEY (ID)
);



/* Create Foreign Keys */

ALTER TABLE p014_user
	ADD FOREIGN KEY (GYM_CODE)
	REFERENCES p014_gym (GYM_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE p014_membership_transfer
	ADD FOREIGN KEY (MARKET_NO)
	REFERENCES p014_market (MARKET_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE p014_market
	ADD FOREIGN KEY (BUYER_ID)
	REFERENCES p014_user (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE p014_market
	ADD FOREIGN KEY (SELLER_ID)
	REFERENCES p014_user (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE p014_notice
	ADD FOREIGN KEY (ID)
	REFERENCES p014_user (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE p014_qna
	ADD FOREIGN KEY (QUESTION_ID)
	REFERENCES p014_user (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE p014_qna
	ADD FOREIGN KEY (ANSWER_ID)
	REFERENCES p014_user (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



